// ESLint flat-config completion depends on a module augmentation of
// @eslint/core's RulesConfig, and two things stand in its way. The dts
// bundler drops `declare module` blocks, so the block is copied from
// src/index.ts into dist here. And @eslint/core ships dual types: ESLint is
// CommonJS, so its own types resolve dist/cjs/types.d.cts, while our ESM
// declaration file resolves dist/esm/types.d.ts; an augmentation from one
// never reaches the other. So the block is emitted twice: inline in
// index.d.ts (ESM resolution) and in eslint-augmentation.d.cts, a CommonJS
// declaration file whose augmentation reaches the types ESLint itself
// uses, referenced from index.d.ts. The worker entry has no exports, so
// its empty declaration stub is removed. Idempotent.

import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const dist = path.join(root, "dist")
const source = fs.readFileSync(path.join(root, "src/index.ts"), "utf8")
const match = source.match(/^declare module "@eslint\/core" \{[\s\S]*?^\}\n/m)
if (!match)
  throw new Error("postbuild: augmentation block not found in src/index.ts")
const block = match[0]

// A module (the `export {}`), so `declare module` augments the resolved
// package instead of declaring an ambient module that would shadow it.
const cts =
  "// Generated by scripts/postbuild.mjs from src/index.ts. Do not edit.\nexport {}\n\n" +
  block
fs.writeFileSync(path.join(dist, "eslint-augmentation.d.cts"), cts)

const reference = '/// <reference path="./eslint-augmentation.d.cts" />\n'
for (const name of ["index.d.ts", "index.d.cts"]) {
  const file = path.join(dist, name)
  if (!fs.existsSync(file)) continue
  let text = fs.readFileSync(file, "utf8")
  if (!text.startsWith(reference)) text = reference + text
  if (
    name === "index.d.ts" &&
    !text.includes('declare module "@eslint/core"')
  ) {
    text = text.trimEnd() + "\n\n" + block
  }
  fs.writeFileSync(file, text)
}
fs.rmSync(path.join(dist, "tailwind-worker.d.ts"), { force: true })
console.log(
  "postbuild: eslint augmentation written to dist (esm inline, cjs via eslint-augmentation.d.cts)"
)
